export const checkout = {
  cart: {
    eyebrow: 'Your cart',
    heading: 'Bouquets in your basket.',
    sub: 'Adjust quantities, remove pieces, or head to checkout when you are ready.',
    empty: {
      heading: 'Your cart is empty.',
      body: 'Browse our handmade bouquets and gifts, each one twisted by hand.',
      ctaLabel: 'Shop flowers',
      ctaTo: '/shop',
    },
    checkoutCta: 'Checkout →',
    continueCta: 'Continue shopping',
    subtotalLabel: 'Subtotal',
    subtotalNote: 'Shipping and delivery details calculated at checkout.',
  },
  drawer: {
    heading: 'Added to cart',
    viewCart: 'View cart',
    checkout: 'Checkout →',
    close: 'Close cart',
  },
  page: {
    seoTitle: 'Checkout',
    eyebrow: 'Checkout',
    heading: 'Delivery details.',
    sub: 'Tell us where it is going and when you need it by, then pay securely below.',
  },
  testMode: {
    banner:
      '✿ Test mode — no real payment is taken. Pay with card 4242 4242 4242 4242, any future expiry and any CVC.',
  },
  payment: {
    legend: 'Payment',
    heading: 'Pay securely',
    sub: 'Card details are handled by Stripe — they never touch our servers.',
    detailsHeading: 'Delivery details',
    editLabel: 'Edit details',
    payCta: 'Pay',
    processing: 'Processing payment…',
    securedNote: 'Secured by Stripe · GST included',
    error: 'Your payment could not be completed. Please check your card details and try again.',
    configError: 'Online payment is not available right now. Please contact us to place your order.',
  },
  delivery: {
    legend: 'Delivery method',
    options: [
      { value: 'delivery', label: 'Deliver to me', note: 'Flat rate shipping across Australia. Free on orders over $150.' },
      { value: 'pickup', label: 'Pick up', note: 'We will message you to arrange a pickup time in Melbourne.' },
    ],
  },
  address: {
    legend: 'Shipping address',
    fields: {
      street: 'Street address',
      suburb: 'Suburb',
      state: 'State',
      postcode: 'Postcode',
    },
    states: [
      { value: 'VIC', label: 'VIC' },
      { value: 'NSW', label: 'NSW' },
      { value: 'QLD', label: 'QLD' },
      { value: 'WA', label: 'WA' },
      { value: 'SA', label: 'SA' },
      { value: 'TAS', label: 'TAS' },
      { value: 'ACT', label: 'ACT' },
      { value: 'NT', label: 'NT' },
    ],
  },
  pickup: {
    heading: 'Pickup in Melbourne',
    body: 'Once your order is placed, Christine will send you a message to arrange a convenient pickup time and location in Melbourne.',
  },
  date: {
    legend: 'Preferred delivery date',
    helper: (days) => `We need at least ${days} days to twist every petal by hand. Choose any date from then on.`,
  },
  contact: {
    legend: 'Your details',
    fields: {
      name: 'Full name',
      email: 'Email',
      phone: 'Phone',
    },
  },
  notes: {
    label: 'Notes (optional)',
    placeholder: 'Card message, colour preferences, special timing — anything you would like us to know.',
  },
  terms: {
    label: 'I have read and agree to the',
    linkLabel: 'terms',
    linkTo: '/terms',
  },
  submit: {
    idle: 'Continue to payment →',
    submitting: 'Setting up payment…',
    error: 'Something went wrong. Please try again or email us directly.',
  },
  summary: {
    heading: 'Order summary',
    subtotal: 'Subtotal',
    subtotalNote: '* excludes shipping fee',
    shipping: 'Shipping',
    shippingFree: 'Free',
    pickup: 'Pickup',
    total: 'Total',
  },
  confirmation: {
    eyebrow: 'Order received',
    heading: 'Thank you — your order is in.',
    sub: 'Your payment went through and a receipt is on its way to your inbox. Christine will start twisting your flowers and be in touch to confirm the finer details. A summary of your order is below.',
    verifying: 'Confirming your payment…',
    referenceLabel: 'Order reference',
    deliveryLabel: 'Delivery',
    dateLabel: 'Preferred date',
    addressLabel: 'Ship to',
    pickupLabel: 'Pickup',
    notesLabel: 'Notes',
    ctaLabel: 'Back to shop',
    ctaTo: '/shop',
    fallback: {
      heading: 'No recent order found.',
      body: 'Looks like you landed here without placing an order.',
      ctaLabel: 'Browse the shop',
      ctaTo: '/shop',
    },
  },
}
